notifications:
  slack: wtsi-cgpit:ptUMR1tkNyZJYd9TpGoss8WR
  email: false

sudo: false

language: ruby

services:
  - docker

script:
  - set -e
  - echo 'Build and check docker image'
  - docker build -t cavemanwrap .
  - docker images | grep -c cavemanwrap
  - echo 'Verify program(s) from each inherited base image - dockstore-cgpbigwig'
  - docker run -t --rm cavemanwrap bwjoin --version
  - echo 'Verify program(s) from each inherited base image - dockstore-cgpmap'
  - docker run -t --rm cavemanwrap bwa_mem.pl -version
  - docker run -t --rm cavemanwrap bammarkduplicates2 --version
  - docker run -t --rm cavemanwrap samtools --version
  - docker run -t --rm cavemanwrap bash -c 'bwa 2>&1 | grep Version'
  - echo 'Verify program(s) from this repo'
  - docker run -t --rm cavemanwrap caveman -v
  - docker run -t --rm cavemanwrap cgpFlagCaVEMan.pl --version
  - docker run -t --rm cavemanwrap caveman.pl -v
